[2024-12-19T05:42:45.495+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T05:42:45.507+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2023-09-28T00:00:00+00:00 [queued]>
[2024-12-19T05:42:45.511+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2023-09-28T00:00:00+00:00 [queued]>
[2024-12-19T05:42:45.512+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T05:42:45.519+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): first_task> on 2023-09-28 00:00:00+00:00
[2024-12-19T05:42:45.524+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3479) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T05:42:45.525+0000] {standard_task_runner.py:72} INFO - Started process 3488 to run task
[2024-12-19T05:42:45.524+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2023-09-28T00:00:00+00:00', '--job-id', '795', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpnih2w_9r']
[2024-12-19T05:42:45.526+0000] {standard_task_runner.py:105} INFO - Job 795: Subtask first_task
[2024-12-19T05:42:45.550+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2023-09-28T00:00:00+00:00 [running]> on host 13c961a72918
[2024-12-19T05:42:45.591+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='code2j' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-28T00:00:00+00:00'
[2024-12-19T05:42:45.592+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T05:42:45.600+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T05:42:45.602+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the first task']
[2024-12-19T05:42:45.606+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T05:42:45.607+0000] {subprocess.py:106} INFO - hello world, this is the first task
[2024-12-19T05:42:45.607+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T05:42:45.617+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T05:42:45.617+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2023-09-28T00:00:00+00:00, execution_date=20230928T000000, start_date=20241219T054245, end_date=20241219T054245
[2024-12-19T05:42:45.664+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T05:42:45.670+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T05:42:45.671+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
