[2024-12-18T13:08:58.101+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:08:58.104+0530] {processor.py:186} INFO - Started process (PID=37301) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:08:58.104+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:08:58.105+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:08:58.104+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:08:58.122+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:08:58.122+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:08:58.122+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:08:58.122+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:08:58.123+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:08:58.203+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-12-18T13:10:57.059+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:10:57.063+0530] {processor.py:186} INFO - Started process (PID=37494) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:10:57.063+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:10:57.064+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:10:57.064+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:10:57.084+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:10:57.084+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:10:57.084+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:10:57.084+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:10:57.085+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:10:57.177+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-12-18T13:13:44.515+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:13:44.519+0530] {processor.py:186} INFO - Started process (PID=37722) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:13:44.519+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:13:44.520+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:13:44.520+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:13:44.537+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:13:44.537+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:13:44.537+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:13:44.537+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:13:44.537+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:13:44.621+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-12-18T13:16:28.751+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:16:28.754+0530] {processor.py:186} INFO - Started process (PID=37974) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:16:28.755+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:16:28.755+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:16:28.755+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:16:28.773+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:16:28.772+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:16:28.773+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:16:28.773+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:16:28.773+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:16:28.857+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-12-18T13:19:18.226+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:19:18.230+0530] {processor.py:186} INFO - Started process (PID=38243) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:19:18.231+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:19:18.231+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:19:18.231+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:19:18.248+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:19:18.248+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:19:18.248+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:19:18.248+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:19:18.249+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:19:18.333+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-18T13:22:14.034+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:22:14.037+0530] {processor.py:186} INFO - Started process (PID=38471) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:22:14.037+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:22:14.038+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:22:14.038+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:22:14.057+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:22:14.056+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:22:14.057+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:22:14.057+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:22:14.057+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:22:14.141+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-18T13:24:57.056+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:24:57.058+0530] {processor.py:186} INFO - Started process (PID=38716) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:24:57.058+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:24:57.059+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:24:57.059+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:24:57.070+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:24:57.070+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:24:57.070+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:24:57.070+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:24:57.070+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:24:57.126+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-12-18T13:27:11.585+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:27:11.587+0530] {processor.py:186} INFO - Started process (PID=39081) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:27:11.587+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:27:11.587+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:27:11.587+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:27:11.598+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:27:11.598+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:27:11.598+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:27:11.598+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:27:11.598+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:27:11.643+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T13:29:15.943+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:29:15.944+0530] {processor.py:186} INFO - Started process (PID=39293) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:29:15.944+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:29:15.945+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:29:15.945+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:29:15.955+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:29:15.955+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:29:15.955+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:29:15.955+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:29:15.955+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:29:16.002+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-12-18T13:31:11.647+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:31:11.649+0530] {processor.py:186} INFO - Started process (PID=39481) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:31:11.649+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:31:11.649+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:31:11.649+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:31:11.659+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:31:11.659+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:31:11.660+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:31:11.659+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:31:11.660+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:31:11.705+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T13:33:37.837+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:33:37.840+0530] {processor.py:186} INFO - Started process (PID=39685) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:33:37.840+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:33:37.841+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:33:37.841+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:33:37.858+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:33:37.857+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:33:37.858+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:33:37.858+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:33:37.858+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:33:37.943+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-12-18T13:36:09.136+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:36:09.137+0530] {processor.py:186} INFO - Started process (PID=39906) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:36:09.137+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:36:09.138+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:36:09.138+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:36:09.148+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:36:09.147+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:36:09.148+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:36:09.148+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:36:09.148+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:36:09.192+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-18T13:38:33.505+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T13:38:33.507+0530] {processor.py:186} INFO - Started process (PID=40101) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:38:33.507+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T13:38:33.508+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:38:33.508+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:38:33.524+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:38:33.523+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T13:38:33.524+0530] {logging_mixin.py:190} INFO - [2024-12-18T13:38:33.524+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T13:38:33.524+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T13:38:33.599+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-12-18T14:12:47.091+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:12:47.094+0530] {processor.py:186} INFO - Started process (PID=40438) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:12:47.094+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:12:47.095+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:12:47.095+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:12:47.117+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:12:47.116+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:12:47.117+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:12:47.117+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:12:47.117+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:12:47.211+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2024-12-18T14:15:41.744+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:15:41.747+0530] {processor.py:186} INFO - Started process (PID=40716) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:15:41.747+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:15:41.748+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:15:41.748+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:15:41.765+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:15:41.765+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:15:41.766+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:15:41.765+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:15:41.766+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:15:41.851+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-18T14:18:30.766+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:18:30.769+0530] {processor.py:186} INFO - Started process (PID=40974) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:18:30.769+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:18:30.770+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:18:30.770+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:18:30.788+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:18:30.787+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:18:30.788+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:18:30.788+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:18:30.788+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:18:30.872+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-18T14:21:15.789+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:21:15.794+0530] {processor.py:186} INFO - Started process (PID=41191) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:21:15.794+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:21:15.794+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:21:15.794+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:21:15.813+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:21:15.813+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:21:15.813+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:21:15.813+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:21:15.813+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:21:15.902+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-12-18T14:24:05.977+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:24:05.980+0530] {processor.py:186} INFO - Started process (PID=41454) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:24:05.980+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:24:05.980+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:24:05.980+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:24:05.998+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:24:05.998+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:24:05.998+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:24:05.998+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:24:05.999+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:24:06.081+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-12-18T14:26:56.647+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:26:56.649+0530] {processor.py:186} INFO - Started process (PID=41707) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:26:56.650+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:26:56.650+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:26:56.650+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:26:56.668+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:26:56.667+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:26:56.668+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:26:56.668+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:26:56.668+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:26:56.760+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-12-18T14:29:43.123+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:29:43.127+0530] {processor.py:186} INFO - Started process (PID=41929) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:29:43.127+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:29:43.128+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:29:43.127+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:29:43.146+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:29:43.145+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:29:43.146+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:29:43.146+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:29:43.146+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:29:43.230+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-12-18T14:32:29.657+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:32:29.660+0530] {processor.py:186} INFO - Started process (PID=42159) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:32:29.661+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:32:29.661+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:32:29.661+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:32:29.680+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:32:29.679+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:32:29.680+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:32:29.680+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:32:29.680+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:32:29.792+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2024-12-18T14:35:23.365+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:35:23.368+0530] {processor.py:186} INFO - Started process (PID=42392) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:35:23.368+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:35:23.369+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:35:23.369+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:35:23.389+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:35:23.389+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:35:23.390+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:35:23.390+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:35:23.390+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:35:23.482+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-12-18T14:38:11.036+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:38:11.038+0530] {processor.py:186} INFO - Started process (PID=42644) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:38:11.038+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:38:11.039+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:38:11.039+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:38:11.058+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:38:11.058+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:38:11.059+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:38:11.058+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:38:11.059+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:38:11.150+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-12-18T14:41:02.700+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:41:02.703+0530] {processor.py:186} INFO - Started process (PID=42884) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:41:02.703+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:41:02.704+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:41:02.704+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:41:02.723+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:41:02.722+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:41:02.723+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:41:02.723+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:41:02.723+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:41:02.808+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-12-18T14:43:50.348+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:43:50.351+0530] {processor.py:186} INFO - Started process (PID=43112) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:43:50.351+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:43:50.352+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:43:50.352+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:43:50.373+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:43:50.373+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:43:50.373+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:43:50.373+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:43:50.373+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:43:50.463+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-12-18T14:46:39.957+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:46:39.959+0530] {processor.py:186} INFO - Started process (PID=43333) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:46:39.960+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:46:39.960+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:46:39.960+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:46:39.979+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:46:39.978+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:46:39.979+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:46:39.979+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:46:39.979+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:46:40.070+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-12-18T14:49:25.724+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:49:25.727+0530] {processor.py:186} INFO - Started process (PID=43582) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:49:25.727+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:49:25.728+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:49:25.728+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:49:25.745+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:49:25.745+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:49:25.745+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:49:25.745+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:49:25.746+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:49:25.828+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-12-18T14:52:16.499+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:52:16.502+0530] {processor.py:186} INFO - Started process (PID=43807) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:52:16.502+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:52:16.503+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:52:16.503+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:52:16.521+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:52:16.521+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:52:16.522+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:52:16.521+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:52:16.522+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:52:16.609+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2024-12-18T14:55:06.607+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:55:06.612+0530] {processor.py:186} INFO - Started process (PID=44052) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:55:06.612+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:55:06.613+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:55:06.613+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:55:06.631+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:55:06.631+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:55:06.631+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:55:06.631+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:55:06.631+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:55:06.722+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-12-18T14:57:57.904+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T14:57:57.906+0530] {processor.py:186} INFO - Started process (PID=44298) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:57:57.906+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T14:57:57.907+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:57:57.907+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:57:57.927+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:57:57.927+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T14:57:57.927+0530] {logging_mixin.py:190} INFO - [2024-12-18T14:57:57.927+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T14:57:57.927+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T14:57:58.018+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-12-18T15:00:42.514+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:00:42.516+0530] {processor.py:186} INFO - Started process (PID=44520) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:00:42.516+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:00:42.517+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:00:42.517+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:00:42.535+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:00:42.534+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:00:42.535+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:00:42.535+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:00:42.535+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:00:42.617+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-18T15:03:28.177+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:03:28.180+0530] {processor.py:186} INFO - Started process (PID=44746) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:03:28.180+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:03:28.181+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:03:28.181+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:03:28.199+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:03:28.199+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:03:28.200+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:03:28.200+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:03:28.200+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:03:28.290+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-12-18T15:06:18.816+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:06:18.819+0530] {processor.py:186} INFO - Started process (PID=44970) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:06:18.820+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:06:18.820+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:06:18.820+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:06:18.839+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:06:18.839+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:06:18.839+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:06:18.839+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:06:18.840+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:06:18.927+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-12-18T15:09:09.015+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:09:09.018+0530] {processor.py:186} INFO - Started process (PID=45190) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:09:09.018+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:09:09.019+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:09:09.019+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:09:09.038+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:09:09.037+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:09:09.038+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:09:09.038+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:09:09.038+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:09:09.127+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2024-12-18T15:11:55.918+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:11:55.921+0530] {processor.py:186} INFO - Started process (PID=45427) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:11:55.922+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:11:55.922+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:11:55.922+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:11:55.940+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:11:55.940+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:11:55.940+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:11:55.940+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:11:55.940+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:11:56.034+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-12-18T15:14:44.704+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:14:44.707+0530] {processor.py:186} INFO - Started process (PID=45688) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:14:44.707+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:14:44.708+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:14:44.708+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:14:44.725+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:14:44.725+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:14:44.725+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:14:44.725+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:14:44.726+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:14:44.808+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-18T15:17:33.939+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:17:33.942+0530] {processor.py:186} INFO - Started process (PID=45922) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:17:33.942+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:17:33.943+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:17:33.942+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:17:33.962+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:17:33.961+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:17:33.962+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:17:33.962+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:17:33.962+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:17:34.057+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-12-18T15:20:23.305+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:20:23.308+0530] {processor.py:186} INFO - Started process (PID=46152) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:20:23.308+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:20:23.309+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:20:23.309+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:20:23.329+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:20:23.329+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:20:23.329+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:20:23.329+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:20:23.329+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:20:23.426+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-12-18T15:23:12.731+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:23:12.734+0530] {processor.py:186} INFO - Started process (PID=46391) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:23:12.734+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:23:12.735+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:23:12.735+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:23:12.755+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:23:12.754+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:23:12.755+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:23:12.755+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:23:12.755+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:23:12.843+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2024-12-18T15:32:36.456+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:32:36.459+0530] {processor.py:186} INFO - Started process (PID=46707) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:32:36.459+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:32:36.460+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:32:36.460+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:32:36.479+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:32:36.479+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:32:36.479+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:32:36.479+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:32:36.479+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:32:36.565+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-12-18T15:35:23.780+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:35:23.783+0530] {processor.py:186} INFO - Started process (PID=46936) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:35:23.783+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:35:23.784+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:35:23.784+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:35:23.802+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:35:23.801+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:35:23.802+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:35:23.802+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:35:23.802+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:35:23.887+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-18T15:38:08.191+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:38:08.194+0530] {processor.py:186} INFO - Started process (PID=47157) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:38:08.194+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:38:08.195+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:38:08.195+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:38:08.212+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:38:08.212+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:38:08.212+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:38:08.212+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:38:08.212+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:38:08.296+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-12-18T15:40:50.324+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:40:50.326+0530] {processor.py:186} INFO - Started process (PID=47380) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:40:50.326+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:40:50.327+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:40:50.327+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:40:50.344+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:40:50.343+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:40:50.344+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:40:50.344+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:40:50.344+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:40:50.427+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-18T15:43:33.481+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T15:43:33.484+0530] {processor.py:186} INFO - Started process (PID=47600) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:43:33.484+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T15:43:33.484+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:43:33.484+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:43:33.501+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:43:33.501+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T15:43:33.502+0530] {logging_mixin.py:190} INFO - [2024-12-18T15:43:33.502+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T15:43:33.502+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T15:43:33.583+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-18T16:02:31.714+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T16:02:31.716+0530] {processor.py:186} INFO - Started process (PID=47875) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:31.716+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:02:31.717+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:02:31.717+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:31.732+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:02:31.732+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:02:31.733+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:02:31.732+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:02:31.733+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:02:31.801+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2024-12-18T16:57:31.496+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T16:57:31.498+0530] {processor.py:186} INFO - Started process (PID=48141) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:57:31.498+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:57:31.498+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:57:31.498+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:57:31.509+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:57:31.509+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:57:31.509+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:57:31.509+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:57:31.509+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:57:31.553+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T16:59:44.268+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T16:59:44.269+0530] {processor.py:186} INFO - Started process (PID=48357) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:59:44.270+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T16:59:44.270+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:59:44.270+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:59:44.280+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:59:44.280+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T16:59:44.281+0530] {logging_mixin.py:190} INFO - [2024-12-18T16:59:44.281+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T16:59:44.281+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T16:59:44.324+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-18T17:01:59.506+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:01:59.508+0530] {processor.py:186} INFO - Started process (PID=48585) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:01:59.508+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:01:59.508+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:01:59.508+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:01:59.519+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:01:59.519+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:01:59.519+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:01:59.519+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:01:59.519+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:01:59.565+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-12-18T17:05:28.192+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:05:28.194+0530] {processor.py:186} INFO - Started process (PID=48718) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:05:28.194+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:05:28.194+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:05:28.194+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:05:28.204+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:05:28.204+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:05:28.205+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:05:28.204+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:05:28.205+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:05:28.250+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T17:07:28.238+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:07:28.240+0530] {processor.py:186} INFO - Started process (PID=48939) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:07:28.240+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:07:28.240+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:07:28.240+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:07:28.251+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:07:28.250+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:07:28.251+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:07:28.251+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:07:28.251+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:07:28.309+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-12-18T17:09:23.521+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:09:23.523+0530] {processor.py:186} INFO - Started process (PID=49122) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:09:23.523+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:09:23.523+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:09:23.523+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:09:23.533+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:09:23.533+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:09:23.533+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:09:23.533+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:09:23.533+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:09:23.579+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-12-18T17:11:37.490+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:11:37.492+0530] {processor.py:186} INFO - Started process (PID=49344) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:11:37.492+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:11:37.492+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:11:37.492+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:11:37.503+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:11:37.502+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:11:37.503+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:11:37.503+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:11:37.503+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:11:37.548+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T17:13:36.613+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:13:36.614+0530] {processor.py:186} INFO - Started process (PID=49559) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:13:36.614+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:13:36.614+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:13:36.614+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:13:36.625+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:13:36.625+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:13:36.625+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:13:36.625+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:13:36.625+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:13:36.671+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-12-18T17:15:29.194+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:15:29.196+0530] {processor.py:186} INFO - Started process (PID=49751) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:15:29.196+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:15:29.196+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:15:29.196+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:15:29.206+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:15:29.206+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:15:29.206+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:15:29.206+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:15:29.206+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:15:29.252+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T17:17:25.593+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:17:25.595+0530] {processor.py:186} INFO - Started process (PID=49937) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:17:25.595+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:17:25.595+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:17:25.595+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:17:25.606+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:17:25.606+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:17:25.606+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:17:25.606+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:17:25.606+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:17:25.652+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-12-18T17:19:30.944+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:19:30.946+0530] {processor.py:186} INFO - Started process (PID=50138) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:19:30.946+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:19:30.946+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:19:30.946+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:19:30.957+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:19:30.957+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:19:30.957+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:19:30.957+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:19:30.957+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:19:31.001+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-12-18T17:21:32.424+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:21:32.426+0530] {processor.py:186} INFO - Started process (PID=50355) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:21:32.426+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:21:32.426+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:21:32.426+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:21:32.436+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:21:32.436+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:21:32.437+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:21:32.437+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:21:32.437+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:21:32.481+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-18T17:23:25.242+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:23:25.243+0530] {processor.py:186} INFO - Started process (PID=50542) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:23:25.244+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:23:25.244+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:23:25.244+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:23:25.254+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:23:25.254+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:23:25.254+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:23:25.254+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:23:25.254+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:23:25.299+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-18T17:25:19.666+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:25:19.667+0530] {processor.py:186} INFO - Started process (PID=50738) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:25:19.667+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:25:19.667+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:25:19.667+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:25:19.677+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:25:19.677+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:25:19.678+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:25:19.678+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:25:19.678+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:25:19.722+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-12-18T17:27:21.124+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:27:21.127+0530] {processor.py:186} INFO - Started process (PID=51009) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:27:21.127+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:27:21.127+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:27:21.127+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:27:21.138+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:27:21.138+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:27:21.138+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:27:21.138+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:27:21.138+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:27:21.183+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-12-18T17:29:33.953+0530] {logging_mixin.py:190} WARNING - /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-18T17:29:33.955+0530] {processor.py:186} INFO - Started process (PID=51228) to work on /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:29:33.955+0530] {processor.py:914} INFO - Processing file /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-18T17:29:33.956+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:29:33.956+0530] {dagbag.py:588} INFO - Filling up the DagBag from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:29:33.967+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:29:33.967+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-18T17:29:33.967+0530] {logging_mixin.py:190} INFO - [2024-12-18T17:29:33.967+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-18T17:29:33.967+0530] {processor.py:927} WARNING - No viable dags retrieved from /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-18T17:29:34.014+0530] {processor.py:208} INFO - Processing /Users/kulyashdahiya/STUDY/DataEngineering/AirflowLearning/py_env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
