[2024-12-19T07:17:56.843+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T07:17:56.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-08-25T00:00:00+00:00 [queued]>
[2024-12-19T07:17:56.860+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-08-25T00:00:00+00:00 [queued]>
[2024-12-19T07:17:56.863+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T07:17:56.877+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2021-08-25 00:00:00+00:00
[2024-12-19T07:17:56.882+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8649) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T07:17:56.884+0000] {standard_task_runner.py:72} INFO - Started process 8662 to run task
[2024-12-19T07:17:56.886+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2021-08-25T00:00:00+00:00', '--job-id', '1565', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpdqan_bfx']
[2024-12-19T07:17:56.890+0000] {standard_task_runner.py:105} INFO - Job 1565: Subtask second_task
[2024-12-19T07:17:56.923+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2021-08-25T00:00:00+00:00 [running]> on host 13c961a72918
[2024-12-19T07:17:56.979+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='code2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-25T00:00:00+00:00'
[2024-12-19T07:17:56.981+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T07:17:56.990+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T07:17:56.991+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-12-19T07:17:56.998+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T07:17:56.999+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1
[2024-12-19T07:17:56.999+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T07:17:57.016+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T07:17:57.017+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2021-08-25T00:00:00+00:00, execution_date=20210825T000000, start_date=20241219T071756, end_date=20241219T071757
[2024-12-19T07:17:57.034+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T07:17:57.043+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T07:17:57.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
