[2024-12-19T07:18:17.263+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T07:18:17.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-27T00:00:00+00:00 [queued]>
[2024-12-19T07:18:17.287+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-27T00:00:00+00:00 [queued]>
[2024-12-19T07:18:17.288+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T07:18:17.308+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2021-10-27 00:00:00+00:00
[2024-12-19T07:18:17.313+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9393) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T07:18:17.314+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2021-10-27T00:00:00+00:00', '--job-id', '1751', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpbzcalr9r']
[2024-12-19T07:18:17.317+0000] {standard_task_runner.py:72} INFO - Started process 9416 to run task
[2024-12-19T07:18:17.318+0000] {standard_task_runner.py:105} INFO - Job 1751: Subtask second_task
[2024-12-19T07:18:17.357+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2021-10-27T00:00:00+00:00 [running]> on host 13c961a72918
[2024-12-19T07:18:17.426+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='code2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-27T00:00:00+00:00'
[2024-12-19T07:18:17.429+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T07:18:17.439+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T07:18:17.439+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-12-19T07:18:17.445+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T07:18:17.446+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1
[2024-12-19T07:18:17.446+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T07:18:17.463+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T07:18:17.464+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2021-10-27T00:00:00+00:00, execution_date=20211027T000000, start_date=20241219T071817, end_date=20241219T071817
[2024-12-19T07:18:17.501+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T07:18:17.516+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T07:18:17.519+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
