[2024-12-19T07:18:36.736+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T07:18:36.748+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2024-12-19T07:18:36.753+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task scheduled__2021-12-28T00:00:00+00:00 [queued]>
[2024-12-19T07:18:36.754+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-19T07:18:36.770+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2021-12-28 00:00:00+00:00
[2024-12-19T07:18:36.774+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10141) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-19T07:18:36.775+0000] {standard_task_runner.py:72} INFO - Started process 10157 to run task
[2024-12-19T07:18:36.776+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'scheduled__2021-12-28T00:00:00+00:00', '--job-id', '1933', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpyf9v646p']
[2024-12-19T07:18:36.778+0000] {standard_task_runner.py:105} INFO - Job 1933: Subtask second_task
[2024-12-19T07:18:36.812+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v2.second_task scheduled__2021-12-28T00:00:00+00:00 [running]> on host 13c961a72918
[2024-12-19T07:18:36.886+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='code2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-28T00:00:00+00:00'
[2024-12-19T07:18:36.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T07:18:36.896+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-19T07:18:36.896+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1']
[2024-12-19T07:18:36.901+0000] {subprocess.py:99} INFO - Output:
[2024-12-19T07:18:36.902+0000] {subprocess.py:106} INFO - hey, I am task2 and will be running after task1
[2024-12-19T07:18:36.903+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-19T07:18:36.919+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T07:18:36.919+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, run_id=scheduled__2021-12-28T00:00:00+00:00, execution_date=20211228T000000, start_date=20241219T071836, end_date=20241219T071836
[2024-12-19T07:18:36.958+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T07:18:36.966+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-19T07:18:36.967+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
